apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-sendnotify
  namespace: monitoring
data:
  wsgi.py: |
    from main import app

    if __name__ == "__main__":
        app.run()

  main.py: |
    import logging
    import os
    from flask import Flask, request, jsonify
    import requests
    from flask_httpauth import HTTPBasicAuth
    from werkzeug.security import generate_password_hash, check_password_hash

    app = Flask(__name__)
    auth = HTTPBasicAuth()

    # Usuários e senhas de exemplo
    users = {
        "admin": generate_password_hash("secret"),
        "user": generate_password_hash("password")
    }

    @auth.verify_password
    def verify_password(username, password):
        if username in users and check_password_hash(users.get(username), password):
            return username
        return None

    @auth.error_handler
    def unauthorized():
        # Retorna uma resposta 401 Unauthorized com o cabeçalho WWW-Authenticate
        return jsonify({"error": "Unauthorized access"}), 401, {'WWW-Authenticate': 'Basic realm="Login Required"'}

    @app.before_request
    def log_request_info():
        app.logger.debug(f"Headers: {request.headers}")
        app.logger.debug(f"Body: {request.get_data()}")

    @app.route('/subscription', methods=['POST'])
    @auth.login_required
    def subscription():
        if not request.is_json:
            app.logger.error("Recebido JSON inválido")
            return jsonify({"error": "Invalid JSON"}), 400

        data = request.get_json()

        if 'ConfirmationURL' in data:
            confirmation_url = data['ConfirmationURL']
            app.logger.debug(f"ConfirmationURL recebido: {confirmation_url}")

            try:
                response = requests.get(confirmation_url, verify=False)
                app.logger.debug(f"Status de confirmação: {response.status_code}")
                app.logger.debug(f"Corpo da resposta: {response.text}")
                response.raise_for_status()  # Verifique se a resposta foi bem-sucedida
                return jsonify({"message": "Subscription confirmed"}), 200
            except requests.RequestException as e:
                app.logger.error(f"Erro ao confirmar a assinatura: {str(e)}")
                return jsonify({"error": str(e)}), 500
        elif 'title' in data:
            title = data['title']
            body = data.get('body', '')
            severity = data.get('severity', '')
            alarm_metadata = data.get('alarmMetaData', [])

            # Adiciona ícone ao título com base no status
            if alarm_metadata:
                alarm = alarm_metadata[0]
                status = alarm.get('status', '')

                
                # Adiciona emojis antes do título com base no status
                if status == 'FIRING':
                    title = f"\n🔥 FIRING 🔥 \n\n*Alarm*: {title}"  # Ícone de fogo antes do título para status FIRING
                elif status == 'OK':
                    title = f"\n✅ RESOLVED ✅ \n\n*Alarm*: {title}"  # Ícone de marca de verificação antes do título para status OK

            message = f"{title}\n*Severity*: {severity}"
            
            if alarm_metadata:
                alarm = alarm_metadata[0]
                status = alarm.get('status', '')
                cloudid =  str(os.environ.get('CLOUDID'))
                namespace = alarm.get('namespace', '')
                query = alarm.get('query', '')
                alarm_summary = alarm.get('alarmSummary', '')
                metric_values = alarm.get('metricValues', [])

                message += f"\n*Status*: {status}\n*CloudID*: {cloudid}\n*Namespace*: {namespace}\n*Query*: {query}\n*Summary*: {alarm_summary}"
                if metric_values:
                    message += f"\n*Metric Values*: {metric_values}"

            webhook_url =  str(os.environ.get('WEBHOOK'))


            payload = {
                "text": message
            }

            headers = {
                "Content-Type": "application/json; charset=utf-8"
            }

            response = requests.post(webhook_url, json=payload, headers=headers)

            if response.status_code == 200:
                app.logger.debug("Mensagem enviada com sucesso para o Google Chat!")
                return jsonify({"message": "Mensagem enviada com sucesso para o Google Chat!"}), 200
            else:
                app.logger.error(f"Falha ao enviar a mensagem para o Google Chat. Código de status: {response.status_code}")
                return jsonify({"error": "Falha ao enviar a mensagem para o Google Chat.", "status_code": response.status_code}), 500
        else:
            app.logger.error("Campos obrigatórios ausentes no corpo da solicitação JSON")
            return jsonify({"error": "Campos obrigatórios ausentes no corpo da solicitação JSON"}), 400

    if __name__ == '__main__':
        # Configure o logger para exibir mensagens de debug
        logging.basicConfig(level=logging.DEBUG)
        app.run(port=8080,debug=True, host='0.0.0.0')