apiVersion: apps/v1
kind: Deployment
metadata:
  name: sendnotify
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: sendnotify
      lbtype: internal
      sendlogs: "true"
  replicas: 1
  template:
    metadata:
      labels:
        app: sendnotify
        version: "1.0.0"
        lbtype: internal
        sendlogs: "true"
    spec:
      serviceAccountName: sa-sendnotify
      containers:
      - name: sendnotify
        image: gru.ocir.io/grrgazcoqsuy/mutant-app-base:ocisendnotify-1.0.0 
        imagePullPolicy: IfNotPresent
        command:
          - "gunicorn"
          - "-w"
          - "1"
          - "-b"
          - "0.0.0.0:8080"
          - "wsgi:app"
          - "--capture-output"
          - "--log-level=debug"
        ports:
        - containerPort: 8080
        env:
        - name: "TZ"
          value: "America/Sao_Paulo"
        - name: 'CLOUD'
          value: 'Oracle Cloud'
        - name: 'CLOUDID'
          value: 'MutantRogue'
        - name: 'WEBHOOK'
          value: 'https://chat.googleapis.com/v1/spaces/AAAAWpyT3Ls/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=c9--2Sqer11Or20uIVP8x7X7_A8CPqV185i1vX8t1Yw' # ALERTA CRÍTICO
        resources:
          limits:
            cpu: "0.2"
            memory: 128Mi
          requests:
            cpu: "0.1"
            memory: 64Mi
        volumeMounts:
          - name: cm-sendnotify
            mountPath: /app/main.py
            subPath: main.py
            readOnly: false
          - name: cm-sendnotify
            mountPath: /app/wsgi.py
            subPath: wsgi.py
            readOnly: false
      volumes:
      - name: cm-sendnotify
        configMap:
          name: cm-sendnotify
