apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: in-sendnotify
  namespace: observability
  labels:
    app: sendnotify
spec:
  ingressClassName: nginx
  rules:
    - host: "sendnotify.emanuelfds.com.br"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: svc-sendnotify
                port:
                  name: sendnotify
