apiVersion: v1
kind: Secret
metadata:
  name: auth-users
  namespace: monitoring
stringData:
  AUTH_ADMIN: "secret"
  AUTH_USER: "password"
  WEBHOOK: "https://chat.googleapis.com/v1/spaces/AAAAtM54aAI/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=_Hxrwqu81ExyWCO5Pmh86cLnSS8WQQDuulpt7Q61zYI"
